name: valve_heights_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  file_provider:
    git: https://github.com/lavruh/file_provider.git
  csv: ^6.0.0
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/template.xlsx
